apiVersion: v1
kind: Service
metadata:
  name: dim-api
  labels:
    app: dim-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: dim-api
  selector:
    app: dim-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dim-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dim-api
  template:
    metadata:
      labels:
        app: dim-api
    spec:
      containers:
        - name: dim-api
          image: destinyitemmanager/dim-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dim-api-secret
                  key: pg_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dim-api-secret
                  key: jwt_secret
            - name: TWIDDLE
              value: tw7
          envFrom:
            - configMapRef:
                name: dim-api-config
          ports:
            - containerPort: 3000
              name: dim-api
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: dim-api
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: dim-api
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 1
