apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: dim-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dim-api
  minReplicas: 2
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
