apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dim-api-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - api.destinyitemmanager.com
        - grafana.destinyitemmanager.com
      secretName: dim-api-tls
  rules:
    - host: api.destinyitemmanager.com
      http:
        paths:
          - backend:
              serviceName: dim-api
              servicePort: 80
    - host: grafana.destinyitemmanager.com
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
