apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "true"
  block-user-agents: '"Test Certificate Info"'
  enable-modsecurity: "true"
  enable-owasp-modsecurity-crs: "false"
  proxy-body-size: "2m"
  use-gzip: "true"
